version: '3.8'

services:
  app:
    image: 'adama93/transactions'
    network_mode: bridge
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adamaseye@
      - DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/adama
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=adamaseye@
      
    ports:
      - "8080:8080"

  db:
    image: postgres:16.0
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adamaseye@
      - POSTGRES_DB=adama
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - adminer-network

volumes:
  postgres-data:

networks:
  adminer-network:    